# Python Numpy Cheatsheet
## What is Numpy ?
A libary consisting of multidimensional array objects and a collection of routines for processing those arrays 

## Why use Numpy ?
High performance on mathematical and logical operations on arrays can be 




## Importing Numpy 


In [84]:
import numpy as np 

## Arrays 

* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

* An ndarray is a (usually fixed-size) multidimensional container of items of the same type and size. The number of dimensions and items in an array is defined by its shape , which is a tuple of N non-negative integers that specify the sizes of each dimension.

### Creating Array

* Syntax : 
`numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)`

#### One Dimensional 

In [85]:
a = np.array([1,2,3])
a

array([1, 2, 3])

#### Two Dimensional 

In [86]:
b = np.array([(1,2,3,4),(7,8,9,10)],dtype=int)
b

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

#### Three Dimensional



In [87]:
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholder 

#### Creating a Zero Arrays

* Syntax : 

```py
numpy.zeros(shape, dtype=float, order='C', *, like=None)
```

##### 1D array of length x all zeros 
`` np.zeros(x)``



In [10]:
np.zeros(3)

array([0., 0., 0.])

##### 2D array of length x all zeros 
`` np.zeros(2,x))``

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

##### 3D array of length x all zeros 
`` np.zeros((3,2,x))``

In [12]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

#### Creating a one Array
* Syntax:
```py
numpy.ones(shape, dtype=None, order='C', *, like=None)
```


In [13]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

#### Creating an array of evenly spaced values (step values)
* Syntax:
```py
numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None) 
```

In [14]:
np.arange(10,25,5)

array([10, 15, 20])

#### Creating an array with random values
```py
numpy.random.random(shape,dtype=None,order='C', *, like=None) 
```

In [18]:
np.random.random((2,2))

array([[0.60501953, 0.6558145 ],
       [0.58046838, 0.53524572]])

## Array Mathematics 


### Arithmetic Operations

#### Substractions 


In [30]:
np.subtract([1,2,3],np.ones(3)) # a - np.ones(3)


array([0., 1., 2.])

#### Addition


In [31]:
np.add([1,2,3],np.ones(3))

array([2., 3., 4.])

#### Division


In [33]:
np.divide([4,8,10],[2,4,5])

array([2., 2., 2.])

#### Multiplication


In [35]:
np.multiply([ 1.5, 4. , 0. ],[ 4. , 10. , 18. ])

array([ 6., 40.,  0.])

#### Dot product

In [37]:
a.dot([4,5,6])

32

### Aggregate Functions

#### Sum

In [38]:
a.sum()

6

#### minimum value

In [39]:
a.min()

1

#### Mean 

In [40]:
a.mean()

2.0

#### Maximum value of an array

In [54]:
b.argmax()

7

#### Median

In [42]:
np.median(b)

5.5

## Copying Arrays



In [131]:
o = a.view() #Create a view of the array with the same data
o

array([1, 2, 3])

In [133]:
np.copy(b) #Create a copy of the array


array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10]])

## Array Manipulation 


### Transposing Array

In [68]:
i = np.transpose(b)
i

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10]])

### Changing Array Shape


In [91]:
h = b.copy()
h.ravel() # flatten the array

array([ 1,  2,  3,  4,  7,  8,  9, 10])

In [83]:
m = c.copy()
m.reshape(3,-2) #Reshape, but don’t change data

array([[1.5, 2. , 3. , 4. ],
       [5. , 6. , 3. , 2. ],
       [1. , 4. , 5. , 6. ]])

### Adding/Removing Elements


In [90]:
m.resize((2,6)) #Return a new array with shape (2,6)
m

array([[1.5, 2. , 3. , 4. , 5. , 6. ],
       [3. , 2. , 1. , 4. , 5. , 6. ]])

In [106]:
x = np.append(h,m) #Append items to an array
x

array([ 1. ,  2. ,  3. ,  4. ,  7. ,  8. ,  9. , 10. ,  1.5,  2. ,  3. ,
        4. ,  5. ,  6. ,  3. ,  2. ,  1. ,  4. ,  5. ,  6. ])

In [102]:
np.insert(h,1,5) # Insert items in a array 

array([ 1,  5,  2,  3,  4,  7,  8,  9, 10])

In [ ]:
np.delete(a,[1]) # Delete items from an array

### Combining Arrays 


In [109]:
y =np.concatenate((a,np.ones(2)),axis=0) #Concatenate arrays 
y

array([1., 2., 3., 1., 1.])

In [115]:
np.vstack((a,np.random.random(3))) #Stack arrays vertically (row-wise)

array([[1.        , 2.        , 3.        ],
       [0.83997178, 0.92391403, 0.20233075]])

In [110]:
np.r_[y,x] #Stack arrays vertically (row-wise)

array([ 1. ,  2. ,  3. ,  1. ,  1. ,  1. ,  2. ,  3. ,  4. ,  7. ,  8. ,
        9. , 10. ,  1.5,  2. ,  3. ,  4. ,  5. ,  6. ,  3. ,  2. ,  1. ,
        4. ,  5. ,  6. ])

In [116]:
np.hstack((a,np.random.random(3))) #Stack arrays horizontally (column-wise)

array([1.        , 2.        , 3.        , 0.06551984, 0.14564732,
       0.68166866])

In [117]:
np.column_stack((a,np.random.random(3))) #Create stacked column-wise arrays 

array([[1.        , 0.94471738],
       [2.        , 0.36652563],
       [3.        , 0.82352155]])

### Splitting Arrays

In [127]:
np.hsplit(x,10) #Split the array horizontally into 10 equal parts

[array([1., 2.]),
 array([3., 4.]),
 array([7., 8.]),
 array([ 9., 10.]),
 array([1.5, 2. ]),
 array([3., 4.]),
 array([5., 6.]),
 array([3., 2.]),
 array([1., 4.]),
 array([5., 6.])]

In [130]:
np.vsplit(c,2) # split the array vertically into 2 equal parts

[array([[[1.5, 2. , 3. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 1.],
         [4., 5., 6.]]])]